### ISSUE TITLE
no-restricted-syntax: enable ForOfStatement

### ISSUE THREAD

**Issue by fleg** [dvpnt/eslint-config-dvpnt#14]
https://github.com/airbnb/javascript/blob/5ebfe3e5b8b72f301228cc1718685d1db9ae5f49/packages/eslint-config-airbnb-base/rules/style.js#L339

**Comment by psixdev** [comment]
pr welcome

**Comment by fleg** [comment]
> pr welcome

haha great nice wonderful

**Comment by shtyr-maxim** [comment]
fixed in 10c08ae50c273305f0a395c21f69f7ca9718d6b4
